Teamroom.Web/ViewModels/FileInput.cs
namespace HobbyClue.Web.ViewModels
{
    public class FileInput
    {
        public string FileName { get; set; }
    }
}

Teamroom.Web/ViewModels/TagListViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using HobbyClue.Data.Models;
using HobbyClue.Web.Configuration.TypeConverters;

namespace HobbyClue.Web.ViewModels
{
    [TypeConverter(typeof(TagListTypeConverter))]
    public class TagListViewModel : List<Tag>
    {
    }
}

Teamroom.Web/Controllers/FileController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HobbyClue.Business.Services;
using HobbyClue.Common.Helpers;
using HobbyClue.Web.Configuration;

namespace HobbyClue.Web.Controllers
{
    public class FileController : Controller
    {
        private readonly IImageService imageService;

        public FileController(IImageService imageService)
        {
            this.imageService = imageService;
        }

        [HttpPost]
        public JsonResult AjaxUpload(HttpPostedFileBase[] files, Guid tempid)
        {
            if (files != null && files.Any())
            {
                // Get a reference to the file that our jQuery sent.  Even with multiple files, they will all be their own request and be the 0 index
                var file = files[0];

                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    if (fileName != null)
                    {
                        FileHelper.CreateDirectoryIfNotExists(Server.MapPath("~//temp"));
                        FileHelper.CreateDirectoryIfNotExists(Server.MapPath("~//temp/uploads"));

                        var path = Path.Combine(Server.MapPath("~/temp/uploads"), fileName);
                        file.SaveAs(path);

                        string thumbNailUrl;
                        var uploadedFile = imageService.UploadImage(path, "CategoryImages", out thumbNailUrl);
                        // Now we need to wire up a response so that the calling script understands what happened
                        System.Web.HttpContext.Current.Response.StatusCode = 200;
                        return new JsonNetResult
                        {
                            Data = new {files = new[] { uploadedFile } }
                        };
                    }
                }
            }
            return new JsonResult();
        }

        [HttpPost]
        public JsonResult SingleFileUpload()
        {
            var file = Request.Files.Get("img");;
            if (file != null)
            {
                var path = Path.Combine(Server.MapPath("~/temp/uploads"), file.FileName);
                file.SaveAs(path);

                string thumbnailUrl;
                var uploadedFileUrl = imageService.UploadImage(path, "GroupImages", out thumbnailUrl);
                // Now we need to wire up a response so that the calling script understands what happened
                System.Web.HttpContext.Current.Response.StatusCode = 200;
                return new JsonNetResult
                {
                    Data = new { code = 0, url = uploadedFileUrl, thumbnailUrl = thumbnailUrl }
                };

                //"{'code': 0, "url": "img.jpg"}"
            }
            return new JsonResult();
        }
    }
}

Teamroom.Web/Views/Shared/EditorTemplates/DateTimeRange.cshtml
@model DateTimeRange
@using HobbyClue.Common.Extensions
@using HobbyClue.Common.Models
@using HobbyClue.Web
@using Teamroom.Web.Views
@{
    var props = ViewData.ModelMetadata.Properties.ToList();
    var validationAttributes = Html.GetUnobtrusiveValidationAttributes("");
}

<div>
    <div class="datetimerange @ViewData.ModelMetadata.PropertyName">
        <div class=" input-group date form_datetime startdate">
            @CalendarBox(props[0].PropertyName, Model != null ? Model.StartDate : DateTime.Now.FormatDateTime(), validationAttributes)
            <span class="separator">to</span>
        </div>
        <div class="input-group date form_datetime enddate">
            @CalendarBox(props[1].PropertyName, Model != null ? Model.EndDate : DateTime.Now.AddHours(4).FormatDateTime(), validationAttributes)
        </div>
    </div>
    @Html.ValidationMessage(props[0].PropertyName)
    @Html.ValidationMessage(props[1].PropertyName)
</div>


@helper CalendarBox(string propertyName, string value, IDictionary<string, object> validationAttributes)
{
    @Html.TextBox(propertyName, value, new RouteValueDictionary(validationAttributes) { { "class", "form-control input-mid" }, { "size", "16" } })
        
    <span class="input-group-btn">
        <button class="btn default date-set @string.Format("btn{0}", propertyName)" type="button"><i class="fa fa-calendar"></i></button>
    </span>
    <div>
        <div class="clearfix"></div>
    </div>
}

Teamroom.Web/Views/Shared/EditorTemplates/FileInput.cshtml
@using Teamroom.Web.Views
@model HobbyClue.Web.ViewModels.FileInput

@using (Html.BeginForm("UploadFile", "File", FormMethod.Post, new {id="fileupload", enctype = "multipart/form-data"}))
{
   <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn green fileinput-button">
                <i class="fa fa-plus"></i>
                <span>Add files...</span>
                <input type="file" name="files" multiple>
            </span>
            <button type="submit" class="btn blue start">
                <i class="fa fa-upload"></i>
                <span>Start upload</span>
            </button>
            <!-- The loading indicator is shown during file processing -->
            <span class="fileupload-loading"></span>
        </div>
        
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width: 0%;">
                </div>
            </div>
            <!-- The extended global progress information -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <table role="presentation">
        <tbody class="files"></tbody>
    </table>
}

Teamroom.Web/Views/Shared/EditorTemplates/ImageUrl.cshtml
@using Teamroom.Web.Views

 @{
     var imageUrl = Model ?? "http://www.placehold.it/100x100/EFEFEF/AAAAAA&amp;text=no+image";
     
        <div class="innercontent">
            <div>
                <input class="hdnImageSrc" type="hidden" name="@string.Format("{0}", ViewData.ModelMetadata.PropertyName)" />
                <div class="fileupload fileupload-new" data-provides="fileupload">
                    <div class="fileupload-new thumbnail" style="width: 100px; height: 100px;">
                        <img class="imageDisplay" src="@imageUrl" alt="" />
                    </div>
                    <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;">
                    </div>
                    <div>
                        <a class="btn default modal-image-gallery" data-toggle="modal" href="#responsive">Select Image</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="responsive" class="modal fade" tabindex="-1" aria-hidden="true" style="z-index: 1031;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Image Gallery</h4>
                    </div>
                    <div class="modal-body">
                        <div class="scroller" style="height:300px" data-always-visible="1" data-rail-visible1="1"></div>
                    </div>
                </div>
            </div>
        </div>
    
        }

        <script>
            $(document).ready(function () {
                var imagegalleryTemplate = Handlebars.compile($("#imagegallery-template").html());
                $.ajax({
                    type: 'GET',
                    url: "/api/image",
                    dataType: 'text'
                }).done(function (data) {
                    var templateHtml = imagegalleryTemplate(jQuery.parseJSON(data));
                    $('.scroller').prepend(templateHtml);
                    wireImageLinks();
                });

                function wireImageLinks() {
                    $('.galleryImg').click(function () {
                        var clickedSrc = $(this).html();
                        var formGroup = $(this).closest('.form-group');
                        $(formGroup).find('.hdnImageSrc:first').val(clickedSrc);
                        $(formGroup).find('.imageDisplay:first').attr('src', clickedSrc);
                    });
                }
            });
        </script>

        <script id="imagegallery-template" type="text/x-handlebars-template">
            <ul>
                {{#each Data}}
                <li>
                    <img src="{{Url}}" style="width:50px; height: 50px;" />
                    <a class="galleryImg" href="#" data-dismiss="modal">{{Url}}</a>
                </li>
                {{/each}}
            </ul>
        </script>

Teamroom.Web/Views/Shared/EditorTemplates/RichTextEditor.cshtml
@using Teamroom.Web.Views
@Html.TextAreaFor(x => x, new { @class = "ckeditor" })

Teamroom.Web/Views/Shared/EditorTemplates/SmartTextArea.cshtml
@using Teamroom.Web.Views
@Html.TextAreaFor(x => x, new{@class="smarttextbox"})

Teamroom.Web/Views/Shared/EditorTemplates/String.cshtml
@using Teamroom.Web.Views
@{
    var placeholder = string.Empty;
    if (ViewData.ModelMetadata.AdditionalValues.ContainsKey("placeholder"))
    {
        placeholder = ViewData.ModelMetadata.AdditionalValues["placeholder"] as string;
    }
}

@Html.TextBoxFor(x => x, new { @class = "form-control input-mid", placeholder = placeholder })

Teamroom.Web/Views/Shared/EditorTemplates/TagList.cshtml
@using HobbyClue.Web.ViewModels
@using Teamroom.Web.Views
@model TagListViewModel

@{
    var tagsJson = Html.Raw(Html.Action("AllTags", "Shared").ToString());
    var selectedTagsJson = Model != null ? Html.Raw(Model.ToJson()) : new HtmlString("[]");
}


<ul id="@ViewData.ModelMetadata.PropertyName" name="@ViewData.ModelMetadata.PropertyName"></ul>

<script>
    $(document).ready(function () {
        var selectedTags = @selectedTagsJson;
        for(var i = 0; i < selectedTags.length; i++) {
            var obj = selectedTags[i];
            $("#@ViewData.ModelMetadata.PropertyName").append('<li>'+obj +'</li>');
        }

        $("#@ViewData.ModelMetadata.PropertyName").tagit({
            availableTags: @tagsJson,
            removeConfirmation: true,
            allowSpaces: true
        });
    });
</script>